import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../globals.css'
import { getDictionary } from './dictionaries'
import { DictionarySetter } from '@/components/config'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
  params: { lang },
}: Readonly<
  {
    children: React.ReactNode
  } & { params: { lang: string } }
>) {
  const dictionary = await getDictionary(lang)

  return (
    <html lang="en">
      <body className={inter.className}>
        <DictionarySetter dictionary={dictionary} />
        {children}
      </body>
    </html>
  )
}
