import type { Metadata } from 'next'
import { inter, ubuntu } from '../fonts'
import '../globals.css'
import { getDictionary } from './dictionaries'
import { DictionarySetter } from '@/components/config'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
  params: { lang },
}: Readonly<
  {
    children: React.ReactNode
  } & { params: { lang: string } }
>) {
  const dictionary = await getDictionary(lang)

  return (
    <html lang="en">
      <body className={`${inter.variable} ${ubuntu.variable}`}>
        <DictionarySetter dictionary={dictionary} />
        <div className="min-h-screen flex flex-col justify-center items-center">
          {children}
        </div>
      </body>
    </html>
  )
}
